//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdeDaJedem.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GdeDaJedemEntities : DbContext
    {
        public GdeDaJedemEntities()
            : base("name=GdeDaJedemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Korisnik> Korisniks { get; set; }
        public DbSet<KorisnikRola> KorisnikRolas { get; set; }
        public DbSet<OceneKomentari> OceneKomentaris { get; set; }
        public DbSet<Opstine> Opstines { get; set; }
        public DbSet<Restoran> Restorans { get; set; }
        public DbSet<Rola> Rolas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TipoviRestorana> TipoviRestoranas { get; set; }
    }
}
