//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdeDaJedem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.KorisnikRolas = new HashSet<KorisnikRola>();
            this.OceneKomentaris = new HashSet<OceneKomentari>();
        }
    
        public int KorisnikID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime DatumUclanjenja { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Telefon { get; set; }
        public System.DateTime DatumRodj { get; set; }
    
        public virtual ICollection<KorisnikRola> KorisnikRolas { get; set; }
        public virtual ICollection<OceneKomentari> OceneKomentaris { get; set; }
    }
}
