//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdeDaJedem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opstine
    {
        public Opstine()
        {
            this.Restorans = new HashSet<Restoran>();
        }
    
        public int opstinaID { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<Restoran> Restorans { get; set; }
    }
}
