//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdeDaJedem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoviRestorana
    {
        public int TipId { get; set; }
        public string Naziv { get; set; }
        public int RestoranID { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
